[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
# Add compiler_builtins to the standard library build
build-std = ["core", "alloc", "compiler_builtins"]
# Activate generation of memcpy, memset, memcmp, memmove
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true
