[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
# Добавляем compiler_builtins в сборку стандартной библиотеки
build-std = ["core", "alloc", "compiler_builtins"]
# Активируем генерацию memcpy, memset, memcmp, memmove
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true
